const tasks=[['⌁','Search water rights','Find public records by owner, file number, basin, or location.'],['✎','File an application','Start a guided permit or water-right application.'],['◉','Explore maps','View basins, rivers, reservoirs, districts, and public datasets.'],['$','Pay fees','Open a secure hosted-payment demonstration.'],['⌖','Find a district office','Locate the right office and contact information.'],['▤','Search historical records','Explore indexed legal archives and photographs.'],['≈','Check water conditions','Review drought, streamflow, and reservoir indicators.'],['?','Get help','Find plain-language guidance and contact support.']];
const grid=document.querySelector('#taskGrid');const dialog=document.querySelector('#prototypeDialog');const title=document.querySelector('#dialogTitle');const copy=document.querySelector('#dialogCopy');
tasks.forEach(([icon,name,desc])=>{const b=document.createElement('button');b.className='task-card';b.innerHTML=`<span>${icon}</span><div><h3>${name}</h3><p>${desc}</p></div>`;b.onclick=()=>openDialog(name,`${desc} This prototype demonstrates the future experience and does not submit official information.`);grid.appendChild(b)});
function openDialog(t,c){title.textContent=t;copy.textContent=c;dialog.showModal()}
document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>dialog.close());
document.querySelector('#mapLaunch').onclick=()=>openDialog('HYDROS Atlas','The production version will embed approved read-only ArcGIS Online applications with accessible summaries, filters, and dataset metadata.');
document.querySelector('#siteSearch').onsubmit=e=>{e.preventDefault();const q=document.querySelector('#searchInput').value.trim();openDialog('Search HYDROS',q?`Prototype search for “${q}”. Future results will combine Drupal content, OCR-indexed archives, GIS metadata, and public water-right records.`:'Enter a search term to explore the prototype.');};
const eras=[['1905','The Office of the State Engineer era begins, establishing an enduring public record of water administration.'],['1930s','Major infrastructure, interstate compacts, and basin-scale planning reshape the state’s water story.'],['1950s','Groundwater science and administration expand alongside New Mexico communities and agriculture.'],['1970s','Environmental awareness, adjudications, and data collection become increasingly interconnected.'],['2000s','Digital mapping and online records begin opening water information to broader public use.'],['Today','HYDROS imagines one accessible digital front door for services, stories, maps, and archives.']];
const tabs=document.querySelector('#timelineTabs');const detail=document.querySelector('#timelineDetail');function showEra(i){[...tabs.children].forEach((b,x)=>b.classList.toggle('active',x===i));detail.innerHTML=`<p class="eyebrow">${eras[i][0]}</p><h3>${eras[i][1]}</h3><p>Future timeline entries can connect historical images, source documents, laws, projects, oral histories, and geographic context.</p>`}eras.forEach(([year],i)=>{const b=document.createElement('button');b.textContent=year;b.setAttribute('role','tab');b.onclick=()=>showEra(i);tabs.appendChild(b)});showEra(0);
const menu=document.querySelector('#menuToggle');const nav=document.querySelector('#primaryNav');menu.onclick=()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)};
document.querySelector('#languageToggle').onclick=()=>openDialog('Language access','The framework supports manual Spanish translations for high-value pages, with editorial review and clear language switching.');