const dialog=document.querySelector('#dialog');const dialogTitle=document.querySelector('#dialogTitle');const dialogText=document.querySelector('#dialogText');function openDialog(title,text){dialogTitle.textContent=title;dialogText.textContent=text;dialog.showModal()}document.querySelectorAll('[data-dialog]').forEach(el=>el.addEventListener('click',()=>{const [title,text]=el.dataset.dialog.split('|');openDialog(title,text)}));document.querySelectorAll('.dialog-x,.dialog-close').forEach(el=>el.addEventListener('click',()=>dialog.close()));dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
const menuButton=document.querySelector('#menuButton'),mainNav=document.querySelector('#mainNav');menuButton?.addEventListener('click',()=>{const open=mainNav.classList.toggle('open');menuButton.setAttribute('aria-expanded',String(open))});
function routeSearch(q){openDialog('Search HYDROS',q?`Prototype search for “${q}”. A production search would combine Drupal content, water-right and well indexes, ArcGIS metadata, OCR archives, drought resources, and official external links.`:'Enter a search term to explore HYDROS.')}document.querySelector('#heroSearch')?.addEventListener('submit',e=>{e.preventDefault();routeSearch(document.querySelector('#heroQuery').value.trim())});document.querySelector('#headerSearch')?.addEventListener('submit',e=>{e.preventDefault();routeSearch(document.querySelector('#headerQuery').value.trim())});
document.querySelector('#languageButton')?.addEventListener('click',()=>openDialog('Acceso en español','La versión de producción ofrecería traducciones manuales y revisadas para páginas de alto valor, navegación bilingüe y rutas claras para solicitar asistencia lingüística.'));
document.querySelectorAll('.layer-list button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.layer-list button').forEach(b=>b.classList.remove('active'));btn.classList.add('active')}));
const officeSelect=document.querySelector('#officeSelect'),officeResult=document.querySelector('#officeResult');officeSelect?.addEventListener('change',()=>{officeResult.innerHTML=officeSelect.value?`<strong>${officeSelect.value}</strong><br>Prototype routing would show the responsible office, service area, phone, hours, directions, forms, notices, and appointment options.`:'Select a region to preview district routing.'});
const knowledge=[
{keys:['drought','dry','arid'],answer:'For current conditions, begin with the New Mexico Drought Portal and the federal Drought.gov New Mexico page. The U.S. Drought Monitor provides the weekly classification map.',links:[['New Mexico Drought Portal','https://drought.nm.gov/'],['Drought.gov New Mexico','https://www.drought.gov/states/new-mexico'],['U.S. Drought Monitor','https://droughtmonitor.unl.edu/CurrentMap/StateDroughtMonitor.aspx?NM']]},
{keys:['streamflow','gauge','river flow','flow'],answer:'USGS Water Data is the primary public source for real-time New Mexico stream gauges. NOAA’s National Water Prediction Service adds forecasts and river observations.',links:[['USGS New Mexico Water Data','https://waterdata.usgs.gov/nm/nwis'],['National Water Prediction Service','https://water.noaa.gov/']]},
{keys:['50-year','50 year','water plan','action plan','mainstream'],answer:'New Mexico’s 50-Year Water Action Plan focuses on long-term resilience, conservation, watershed health, infrastructure, new supplies, science, and community action. MainStream New Mexico is the public engagement pathway featured in this prototype.',links:[['MainStream New Mexico','https://mainstreamnm.org/']]},
{keys:['water right','rights','ownership','file number'],answer:'To research a water right, gather the owner name, file number, basin, county, legal description, or point of diversion. Use official OSE records for authoritative information and contact the responsible district office for interpretation or filing guidance.',links:[['Official OSE website','https://www.ose.nm.gov/']]},
{keys:['well','driller','well log','domestic well'],answer:'Well questions may involve permitting, construction records, drillers, location, depth, or status. The production HYDROS experience would route the user to the official OSE well and district resources.',links:[['Official OSE website','https://www.ose.nm.gov/']]},
{keys:['acequia','mayordomo','commission'],answer:'Acequia questions can involve local governance, infrastructure, water rights, bylaws, funding, and community traditions. Consult official state resources and acequia organizations, and verify legal questions with the appropriate authority.',links:[['NM Acequia Commission','https://www.nmacequiacommission.state.nm.us/'],['NM Acequia Association','https://www.nmacequia.org/']]},
{keys:['snow','snowpack','snotel'],answer:'NRCS Snow Survey and Water Supply provides SNOTEL and basin snowpack information used in seasonal water-supply analysis.',links:[['NRCS Snow Survey','https://www.nrcs.usda.gov/wps/portal/wcc/home/']]},
{keys:['compact','rio grande compact','pecos compact'],answer:'Interstate stream compacts define obligations among states and are supported by accounting, river operations, technical reports, meetings, and legal records. Use OSE and Interstate Stream Commission sources for official information.',links:[['OSE / Interstate Stream Commission','https://www.ose.nm.gov/ISC/']]}
];
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function aiAnswer(q){const lower=q.toLowerCase();const hit=knowledge.find(k=>k.keys.some(key=>lower.includes(key)));if(hit){return `${hit.answer}<div class="ai-links">${hit.links.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener">${label} ↗</a>`).join('')}</div><small>Confidence: high for resource routing; verify substantive details with the linked authority.</small>`}return `I can help route questions about water rights, wells, drought, streamflow, snowpack, acequias, compacts, maps, records, and the 50-Year Water Action Plan. For an official determination, filing deadline, enforcement matter, or emergency, contact OSE or the responsible public authority.<div class="ai-links"><a href="https://www.ose.nm.gov/" target="_blank" rel="noopener">Official OSE website ↗</a><a href="#resources">Browse HYDROS resources</a></div><small>Confidence: general guidance only.</small>`}
const chatLog=document.querySelector('#chatLog'),chatForm=document.querySelector('#chatForm'),chatInput=document.querySelector('#chatInput');function submitQuestion(q){if(!q)return;const user=document.createElement('div');user.className='message user';user.innerHTML=`<b>You</b><p>${escapeHtml(q)}</p>`;chatLog.appendChild(user);const typing=document.createElement('div');typing.className='message bot';typing.innerHTML='<b>HYDROS AI</b><p>Reviewing New Mexico water resources…</p>';chatLog.appendChild(typing);chatLog.scrollTop=chatLog.scrollHeight;setTimeout(()=>{typing.innerHTML=`<b>HYDROS AI</b><p>${aiAnswer(q)}</p>`;chatLog.scrollTop=chatLog.scrollHeight},450)}chatForm?.addEventListener('submit',e=>{e.preventDefault();const q=chatInput.value.trim();chatInput.value='';submitQuestion(q)});document.querySelectorAll('.suggestions button').forEach(btn=>btn.addEventListener('click',()=>submitQuestion(btn.textContent)));
